apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K1nDropAllCapabilities
metadata:
  name: require-drop-all-capabilities
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
