apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K1nDenyHostPathVolumes
metadata:
  name: deny-hostpath-volumes
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
