apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K1nNonRootContainer
metadata:
  name: require-non-root-containers
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
