apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K1nReadOnlyRootFS
metadata:
  name: require-read-only-root-fs
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
